/**
 * The bundled default cube for ranked matchmaking: 360 well-known cube
 * staples. On first use the names are resolved via Scryfall and persisted as
 * a system cube row (owner "system"), so the list never re-resolves across
 * restarts. Names Scryfall cannot resolve simply drop out (count is logged).
 */
import type { CardData } from "@mtg-cube/shared";
import type { CubeFullRow, StoredCubeCards } from "./db.js";
import { SYSTEM_OWNER_ID, getCubeById, insertCube, renameCube } from "./db.js";
import { resolveCardNames } from "./scryfall.js";

export const DEFAULT_CUBE_ID = "system-default-cube";
export const DEFAULT_CUBE_NAME = "Classic Cube Staples";
export { SYSTEM_OWNER_ID } from "./db.js";

/** ~360 real cube staples across every color and archetype. Exact Scryfall names. */
export const DEFAULT_CUBE_CARD_NAMES: readonly string[] = [
  // -- White (54) -----------------------------------------------------------
  "Mother of Runes",
  "Giver of Runes",
  "Thraben Inspector",
  "Student of Warfare",
  "Soldier of the Pantheon",
  "Kytheon, Hero of Akros",
  "Selfless Spirit",
  "Stoneforge Mystic",
  "Wall of Omens",
  "Thalia, Guardian of Thraben",
  "Adanto Vanguard",
  "Containment Priest",
  "Precinct Captain",
  "Blade Splicer",
  "Brimaz, King of Oreskos",
  "Flickerwisp",
  "Monastery Mentor",
  "Silverblade Paladin",
  "Mirran Crusader",
  "Recruiter of the Guard",
  "Ranger-Captain of Eos",
  "Skyclave Apparition",
  "Hero of Bladehold",
  "Restoration Angel",
  "Emeria Angel",
  "Archangel Avacyn",
  "Baneslayer Angel",
  "Lyra Dawnbringer",
  "Reveillark",
  "Sun Titan",
  "Elesh Norn, Grand Cenobite",
  "Angel of Invention",
  "Palace Jailer",
  "Leonin Relic-Warder",
  "Swords to Plowshares",
  "Path to Exile",
  "Condemn",
  "Disenchant",
  "Balance",
  "Spectral Procession",
  "Lingering Souls",
  "Armageddon",
  "Wrath of God",
  "Day of Judgment",
  "Terminus",
  "Council's Judgment",
  "Oblivion Ring",
  "Banishing Light",
  "Land Tax",
  "History of Benalia",
  "Elspeth, Knight-Errant",
  "Elspeth, Sun's Champion",
  "Gideon, Ally of Zendikar",
  "Cathar Commando",
  // -- Blue (54) ------------------------------------------------------------
  "Pteramander",
  "Delver of Secrets",
  "Baral, Chief of Compliance",
  "Jace, Vryn's Prodigy",
  "Snapcaster Mage",
  "Looter il-Kor",
  "Merfolk Looter",
  "Augur of Bolas",
  "Thing in the Ice",
  "Phantasmal Image",
  "True-Name Nemesis",
  "Vendilion Clique",
  "Spellseeker",
  "Champion of Wits",
  "Glen Elendra Archmage",
  "Sower of Temptation",
  "Venser, Shaper Savant",
  "Riftwing Cloudskate",
  "Whirler Rogue",
  "Mulldrifter",
  "Consecrated Sphinx",
  "Torrential Gearhulk",
  "Frost Titan",
  "Aetherling",
  "Brainstorm",
  "Ponder",
  "Preordain",
  "Serum Visions",
  "Opt",
  "Ancestral Vision",
  "Counterspell",
  "Mana Leak",
  "Remand",
  "Miscalculation",
  "Daze",
  "Force of Negation",
  "Cryptic Command",
  "Mystic Confluence",
  "Force of Will",
  "Repeal",
  "Into the Roil",
  "Cyclonic Rift",
  "Fact or Fiction",
  "Gifts Ungiven",
  "Compulsive Research",
  "Thirst for Knowledge",
  "Dig Through Time",
  "Treasure Cruise",
  "Time Warp",
  "Show and Tell",
  "Control Magic",
  "Treachery",
  "Jace, the Mind Sculptor",
  "Jace Beleren",
  // -- Black (54) -----------------------------------------------------------
  "Diregraf Ghoul",
  "Bloodsoaked Champion",
  "Gravecrawler",
  "Knight of the Ebon Legion",
  "Dark Confidant",
  "Kitesail Freebooter",
  "Pack Rat",
  "Vampire Hexmage",
  "Bone Shredder",
  "Hypnotic Specter",
  "Vampire Nighthawk",
  "Ophiomancer",
  "Woe Strider",
  "Midnight Reaper",
  "Rotting Regisaur",
  "Gonti, Lord of Luxury",
  "Shriekmaw",
  "Custodi Lich",
  "Grave Titan",
  "Massacre Wurm",
  "Sheoldred, Whispering One",
  "Griselbrand",
  "Tasigur, the Golden Fang",
  "Thoughtseize",
  "Inquisition of Kozilek",
  "Duress",
  "Fatal Push",
  "Dark Ritual",
  "Vampiric Tutor",
  "Demonic Tutor",
  "Diabolic Edict",
  "Go for the Throat",
  "Doom Blade",
  "Hero's Downfall",
  "Dismember",
  "Toxic Deluge",
  "Damnation",
  "Languish",
  "Living Death",
  "Reanimate",
  "Animate Dead",
  "Exhume",
  "Necromancy",
  "Yawgmoth's Will",
  "Mind Twist",
  "Hymn to Tourach",
  "Night's Whisper",
  "Sign in Blood",
  "Phyrexian Arena",
  "Bitterblossom",
  "Recurring Nightmare",
  "Liliana of the Veil",
  "Liliana, the Last Hope",
  "Murderous Rider",
  // -- Red (54) -------------------------------------------------------------
  "Goblin Guide",
  "Monastery Swiftspear",
  "Zurgo Bellstriker",
  "Grim Lavamancer",
  "Dragonmaster Outcast",
  "Kari Zev, Skyship Raider",
  "Young Pyromancer",
  "Abbot of Keral Keep",
  "Eidolon of the Great Revel",
  "Robber of the Rich",
  "Goblin Rabblemaster",
  "Legion Warboss",
  "Imperial Recruiter",
  "Seasoned Pyromancer",
  "Pia and Kiran Nalaar",
  "Hazoret the Fervent",
  "Hellrider",
  "Flametongue Kavu",
  "Rekindling Phoenix",
  "Glorybringer",
  "Thundermaw Hellkite",
  "Stormbreath Dragon",
  "Inferno Titan",
  "Zealous Conscripts",
  "Siege-Gang Commander",
  "Greater Gargadon",
  "Lightning Bolt",
  "Chain Lightning",
  "Burst Lightning",
  "Firebolt",
  "Magma Jet",
  "Incinerate",
  "Abrade",
  "Lightning Strike",
  "Fireblast",
  "Exquisite Firecraft",
  "Flame Slash",
  "Arc Trail",
  "Pyroclasm",
  "Sweltering Suns",
  "Fiery Confluence",
  "Wheel of Fortune",
  "Faithless Looting",
  "Light Up the Stage",
  "Chandra, Torch of Defiance",
  "Koth of the Hammer",
  "Sneak Attack",
  "Sulfuric Vortex",
  "Goblin Bombardment",
  "Mizzium Mortars",
  "Banefire",
  "Char",
  "Embereth Shieldbreaker",
  "Bonecrusher Giant",
  // -- Green (54) -----------------------------------------------------------
  "Llanowar Elves",
  "Elvish Mystic",
  "Fyndhorn Elves",
  "Avacyn's Pilgrim",
  "Birds of Paradise",
  "Joraga Treespeaker",
  "Arbor Elf",
  "Sylvan Caryatid",
  "Rofellos, Llanowar Emissary",
  "Sakura-Tribe Elder",
  "Wall of Roots",
  "Lotus Cobra",
  "Scavenging Ooze",
  "Fauna Shaman",
  "Devoted Druid",
  "Eternal Witness",
  "Ramunap Excavator",
  "Reclamation Sage",
  "Courser of Kruphix",
  "Tireless Tracker",
  "Nissa, Vastwood Seer",
  "Yavimaya Elder",
  "Oracle of Mul Daya",
  "Master of the Wild Hunt",
  "Polukranos, World Eater",
  "Thrun, the Last Troll",
  "Obstinate Baloth",
  "Acidic Slime",
  "Thragtusk",
  "Deranged Hermit",
  "Whisperwood Elemental",
  "Biogenic Ooze",
  "Primeval Titan",
  "Avenger of Zendikar",
  "Hornet Queen",
  "Craterhoof Behemoth",
  "Terastodon",
  "Woodfall Primus",
  "Questing Beast",
  "Green Sun's Zenith",
  "Beast Within",
  "Regrowth",
  "Kodama's Reach",
  "Cultivate",
  "Rampant Growth",
  "Nature's Lore",
  "Harmonize",
  "Plow Under",
  "Natural Order",
  "Tooth and Nail",
  "Sylvan Library",
  "Survival of the Fittest",
  "Garruk Wildspeaker",
  "Vivien Reid",
  // -- Multicolor (30) ------------------------------------------------------
  "Geist of Saint Traft",
  "Teferi, Hero of Dominaria",
  "Supreme Verdict",
  "Baleful Strix",
  "Thief of Sanity",
  "The Scarab God",
  "Dreadbore",
  "Kolaghan's Command",
  "Rakdos, Lord of Riots",
  "Bloodbraid Elf",
  "Dragonlord Atarka",
  "Wrenn and Six",
  "Kitchen Finks",
  "Knight of the Reliquary",
  "Voice of Resurgence",
  "Vindicate",
  "Anguished Unmaking",
  "Sorin, Lord of Innistrad",
  "Dack Fayden",
  "Electrolyze",
  "Prophetic Bolt",
  "Abrupt Decay",
  "Maelstrom Pulse",
  "The Gitrog Monster",
  "Figure of Destiny",
  "Ajani Vengeant",
  "Nahiri, the Harbinger",
  "Edric, Spymaster of Trest",
  "Trygon Predator",
  "Kiora, the Crashing Wave",
  // -- Colorless & artifacts (40) -------------------------------------------
  "Bomat Courier",
  "Phyrexian Revoker",
  "Metallic Mimic",
  "Solemn Simulacrum",
  "Wurmcoil Engine",
  "Myr Battlesphere",
  "Steel Hellkite",
  "Duplicant",
  "Karn Liberated",
  "Ugin, the Spirit Dragon",
  "Emrakul, the Aeons Torn",
  "Kozilek, Butcher of Truth",
  "Ulamog, the Ceaseless Hunger",
  "Sol Ring",
  "Mana Vault",
  "Grim Monolith",
  "Mind Stone",
  "Coldsteel Heart",
  "Worn Powerstone",
  "Thran Dynamo",
  "Gilded Lotus",
  "Everflowing Chalice",
  "Azorius Signet",
  "Dimir Signet",
  "Rakdos Signet",
  "Gruul Signet",
  "Selesnya Signet",
  "Orzhov Signet",
  "Izzet Signet",
  "Golgari Signet",
  "Boros Signet",
  "Simic Signet",
  "Skullclamp",
  "Umezawa's Jitte",
  "Sword of Fire and Ice",
  "Sword of Feast and Famine",
  "Batterskull",
  "Lightning Greaves",
  "Smuggler's Copter",
  "Coalition Relic",
  // -- Lands (20) -----------------------------------------------------------
  "Flooded Strand",
  "Polluted Delta",
  "Bloodstained Mire",
  "Wooded Foothills",
  "Windswept Heath",
  "Marsh Flats",
  "Scalding Tarn",
  "Verdant Catacombs",
  "Arid Mesa",
  "Misty Rainforest",
  "Hallowed Fountain",
  "Watery Grave",
  "Blood Crypt",
  "Stomping Ground",
  "Temple Garden",
  "Godless Shrine",
  "Steam Vents",
  "Overgrown Tomb",
  "Sacred Foundry",
  "Breeding Pool",
];

let ensuring: Promise<CubeFullRow> | null = null;

/** v2.1: DBs seeded before the rename carry the old name — fix it in place. */
function withCurrentName(row: CubeFullRow): CubeFullRow {
  if (row.name !== DEFAULT_CUBE_NAME) {
    renameCube(DEFAULT_CUBE_ID, DEFAULT_CUBE_NAME);
    console.log(`[defaultCube] renamed "${row.name}" -> "${DEFAULT_CUBE_NAME}"`);
    return { ...row, name: DEFAULT_CUBE_NAME };
  }
  return row;
}

/**
 * Return the persisted system default cube, resolving + persisting it on
 * first use. Concurrent callers share one in-flight resolution.
 */
export function ensureDefaultCube(): Promise<CubeFullRow> {
  const existing = getCubeById(DEFAULT_CUBE_ID);
  if (existing) return Promise.resolve(withCurrentName(existing));
  ensuring ??= (async () => {
    try {
      // Re-check inside the lock: another caller may have just persisted it.
      const row = getCubeById(DEFAULT_CUBE_ID);
      if (row) return withCurrentName(row);

      const names = [...DEFAULT_CUBE_CARD_NAMES];
      const { byName, unresolved } = await resolveCardNames(names);
      const cardIds: string[] = [];
      const cards: Record<string, CardData> = {};
      for (const name of names) {
        const card = byName.get(name);
        if (!card) continue; // unresolved names simply drop out
        cards[card.id] = card;
        cardIds.push(card.id);
      }
      if (cardIds.length < 180) {
        throw new Error(
          `Default cube resolution failed: only ${cardIds.length}/${names.length} cards resolved`
        );
      }
      const stored: StoredCubeCards = { cardIds, cards };
      insertCube({
        id: DEFAULT_CUBE_ID,
        ownerId: SYSTEM_OWNER_ID,
        name: DEFAULT_CUBE_NAME,
        listText: names.join("\n"),
        cards: stored,
        unresolved,
        rankedEligible: true,
      });
      console.log(
        `[defaultCube] resolved ${cardIds.length}/${names.length} cards ` +
          `(${unresolved.length} unresolved dropped); persisted as system cube`
      );
      const persisted = getCubeById(DEFAULT_CUBE_ID);
      if (!persisted) throw new Error("Default cube vanished after insert");
      return persisted;
    } finally {
      ensuring = null; // allow a retry if resolution failed
    }
  })();
  return ensuring;
}
